name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: "14.15.0"
    - name: npm ci
      run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm test
